//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public int User_ID { get; set; }
        public int Subject_ID { get; set; }
        public int Group_ID { get; set; }
        public int NumberLessons { get; set; }
    }
}
