//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        public int ID_Shedule { get; set; }
        public int Room_ID { get; set; }
        public int Order_ID { get; set; }
        public int Couple_ID { get; set; }
        public int DayOfWeek { get; set; }
        public bool NumDem { get; set; }
    }
}
